# -*- coding: utf-8 -*-
"""lab_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJmkah6NiUBvyeCzXd0o2yuoY_400p75
"""

# Part 0
import os

from google.colab import userdata

API_KEY = userdata.get("GROQ_API_KEY")

from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",
)
MODEL = "llama-3.3-70b-versatile"

print("Client ready.")

# Part 1.1
def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
            temperature=0.7, max_tokens=500):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response

result = ask_llm("Simple definition of microfinance")
print(result.choices[0].message.content)
print(result.usage)

"""## Part 1.1 Student Reasoning - Anatomy of a call
1. Difference between system and use roles:
The system sets the model's behaviour for the whole conversation, an example being; "You are a loan officer, focus on facts". The user message is the actual question being asked in that context, an example being; "Summarize this loan application".

2. A token is a chunk of text that the model processes. It is roughly a work or part of a word. Tokens matter because usage is measured based on token count.
"""

# Part 1.2
question = "Suggest a name for a savings product for market traders in Accra."

print(" For Temperature=0.0")
print("---------------------")
for i in range(5):
    r = ask_llm(question, temperature=0.0)
    print(i + 1, ".", r.choices[0].message.content, )
    print()

print()
print(" For Temperature=1.2")
print("---------------------")
for i in range(5):
    r = ask_llm(question, temperature=1.2)
    print(i + 1, ". ", r.choices[0].message.content, )
    print()

"""## Part 1.2 Student Reasoning - Temperature
1. At temperature=0.0, all 5 answers were roughly the same, the model kept suggesting very similar product names.
At temperature=1.2, the 5 answers were varied with different product names.

2. Temperature controls how much randomness the model uses whe picking the next word.
For the loan decision-support system temperature=0.0 is much more appropriate because certain things such as the summarization need to be factual and consistent. Temperature=1.2 would introduce unecessary randomness which is not ideal for a system that will support real financial decisions.
"""

# Section 2
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

# Part 3.1
SUMMARY_PROMPT_V1 = "Summarize this: {letter}"
for lid in ["L002", "L006"]:
    prompt = SUMMARY_PROMPT_V1.format(letter=LETTERS[lid])
    r = ask_llm(prompt)
    print(lid, ":", sep="")
    print(r.choices[0].message.content)
    print()

SUMMARY_SYSTEM_V2 = (
    "You are an assistant to a microfinance loan officer. "
    "Summarize loan application letters factually and neutrally. "
    "Do not invent any detail. "
    "Keep the summary to 3-4 sentences."
)

SUMMARY_PROMPT_V2 = "Summarize this loan application:\n\n{letter}"

for lid in ["L002", "L006"]:
    prompt = SUMMARY_PROMPT_V2.format(letter=LETTERS[lid])
    r = ask_llm(prompt, system_prompt=SUMMARY_SYSTEM_V2, temperature=0)
    print(lid, ":", sep="")
    print(r.choices[0].message.content)
    print()

"""## Part 3.1 Student Reasoning - Summarization prompts
1. The naive prompt gave the model no guidance on tone, length, or how to be careful with facts.
For L006, V1 stated as fact that kofi has no prior experience, it did not differentiate between what was actually stated and what was just assumed. The were also no instructions constraining the summary length and style. V2 amde some fixes by adding a system prompt defining the model's role, instructions not to invent or assume any detail not explicitly stated and a length constraint.

2. The failure mode is hallucination, which is when a model generates corrrect sounding information which is not actually correct. Since the summary would inform a real financial decision, if the model invented any detail, actions taken will be based on false information.

"""

# Part 3.2
EXTRACT_SYSTEM = (
    "You are a data extraction assistant for a microfinance loan officer. "
    "Extract information from loan application letters into strict JSON. "
    "Return ONLY a JSON object with EXACTLY these keys: "
    "applicant_name (string), amount_ghs (number), purpose (string), "
    "monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean), "
    "repayment_months (number or null). "
    "If a field is not stated in the letter, use null. Do not guess."
)

FEWSHOT_LETTER = """Dear Sir,
My name is Ama Serwaa, a hairdresser in Tema. I am requesting GHS 6,000 to buy new
hairdryers and chairs. My shop currently earns about GHS 700 monthly. My brother will
guarantee the loan. I propose to repay over 10 months."""

FEWSHOT_JSON = """{
  "applicant_name": "Ama Serwaa",
  "amount_ghs": 6000,
  "purpose": "buy new hairdryers and chairs",
  "monthly_profit_ghs": 700,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}"""

EXTRACT_PROMPT = """Here is an example.

Letter:
{fewshot_letter}

JSON:
{fewshot_json}

Now extract the same fields from this letter. Return ONLY the JSON object, nothing else.

Letter:
{letter}

JSON:"""

import json

def extract_fields(letter_text, temperature=0):
    prompt = EXTRACT_PROMPT.format(
        fewshot_letter=FEWSHOT_LETTER,
        fewshot_json=FEWSHOT_JSON,
        letter=letter_text,
    )
    r = ask_llm(prompt, system_prompt=EXTRACT_SYSTEM, temperature=temperature, max_tokens=300)
    raw = r.choices[0].message.content.strip()

    if raw.startswith("```"):
        raw = raw.strip("`")
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        print("Warning: could not parse JSON for this letter.")
        print("Raw output was:", raw)
        return None

import pandas as pd

rows = []
for lid in LETTERS:
    fields = extract_fields(LETTERS[lid])
    if fields is not None:
        fields["letter_id"] = lid
        rows.append(fields)

df = pd.DataFrame(rows)
df = df[["letter_id", "applicant_name", "amount_ghs", "purpose",
         "monthly_profit_ghs", "has_collateral_or_guarantor", "repayment_months"]]
df

"""## Part 3.2 Student Reasoning - Structured extraction
1. If the example came from one of the six letters, the model would have seen the answer for that letter and would not test the actual extraction capability.

2. Without it, it is likely that the model will fill in every field with a value the letter did not state. The instruction, "use null, do not guess", forces the model to differentiate between what is stated and what is unkown.

3. Temperature=0 is the right choice for extraction because it is meant to pull out facts that are already present in the text, so variation has no benefit here.
"""

# Part 3.3
BRIEF_SYSTEM = (
    "You are an assistant to a microfinance loan officer in Ghana. "
    "You help the officer review applications by organizing information — "
    "you do NOT make the final lending decision. "
    "Never output 'approve' or 'reject'. Final decisions are made by a human officer."
)

BRIEF_PROMPT = """Here is a loan application letter and the structured data extracted from it.

Letter:
{letter}

Extracted data:
{extracted_json}

Write a decision-support brief with exactly these four sections:
1. Strengths (bullet points, grounded only in the letter)
2. Risks / red flags (bullet points)
3. Missing information the officer should request
4. Suggested next step (e.g. "invite for interview", "request documents", "flag for senior review") — do NOT say approve or reject."""

def make_brief(letter_text, extracted_fields):
    prompt = BRIEF_PROMPT.format(
        letter=letter_text,
        extracted_json=json.dumps(extracted_fields, indent=2),
    )
    r = ask_llm(prompt, system_prompt=BRIEF_SYSTEM, temperature=0, max_tokens=500)
    return r.choices[0].message.content

briefs = {}
for row in rows:
    lid = row["letter_id"]
    briefs[lid] = make_brief(LETTERS[lid], row)

for lid in ["L001", "L002", "L006"]:
    print(lid, ":", sep="")
    print(briefs[lid])
    print()

"""## Part 3.3 Student Reasoning - Decision support
Why we forbid the model from outputting "approve"/"reject":

Practical reason:
The model does not have access to the actual policy of the loan institution, so any decision it would output would not reflect the rules of the institution, the model was not given.

Ethical reason:
The final decision would affect a person's livelihood. The model can misjudge context which is not contained in the letter alone. The final decision should be left to a human, so that someone can be held accountable or responsible for the decision.
"""

# Commented out IPython magic to ensure Python compatibility.
# # Part 3.4
# %%writefile prompts.py
# SUMMARY_SYSTEM_V2 = """You are an assistant to a microfinance loan officer. Summarize loan application letters factually and neutrally. Do not invent or assume any detail that is not explicitly stated in the letter. Keep the summary to 3-4 sentences."""
# 
# SUMMARY_PROMPT_V2 = "Summarize this loan application:\n\n{letter}"
# 
# EXTRACT_SYSTEM = """You are a data extraction assistant for a microfinance loan officer. Extract information from loan application letters into strict JSON. Return ONLY a JSON object with EXACTLY these keys: applicant_name (string), amount_ghs (number), purpose (string), monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean), repayment_months (number or null). If a field is not stated in the letter, use null. Do not guess."""
# 
# EXTRACT_PROMPT = """Here is an example.
# 
# Letter:
# {fewshot_letter}
# 
# JSON:
# {fewshot_json}
# 
# Now extract the same fields from this letter. Return ONLY the JSON object, nothing else.
# 
# Letter:
# {letter}
# 
# JSON:"""
# 
# BRIEF_SYSTEM = """You are an assistant to a microfinance loan officer in Ghana. You help the officer review applications by organizing information — you do NOT make the final lending decision. Never output 'approve' or 'reject'. Final decisions are made by a human officer."""
# 
# BRIEF_PROMPT = """Here is a loan application letter and the structured data extracted from it.
# 
# Letter:
# {letter}
# 
# Extracted data:
# {extracted_json}
# 
# Write a decision-support brief with exactly these four sections:
# 1. Strengths (bullet points, grounded only in the letter)
# 2. Risks / red flags (bullet points)
# 3. Missing information the officer should request
# 4. Suggested next step (e.g. "invite for interview", "request documents", "flag for senior review") — do NOT say approve or reject."""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# from google.colab import userdata
# import os
# 
# GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
# GITHUB_USER = "TheG0AT-0"
# REPO_NAME = "lab-4-llm-decision-support"
# 
# repo_url = f"https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git"
# 
# !git clone {repo_url}
# !cp prompts.py {REPO_NAME}/
# %cd {REPO_NAME}
# !git config user.email "ivanaddo80@gmail.com"
# !git config user.name "TheG0AT-0"
# !git add prompts.py
# !git commit -m "Part 3.4: prompts.py with final prompt templates"
# !git push

# Part 4.1
correct = 0
total = 0

for lid in GOLD:
    gold_fields = GOLD[lid]
    extracted = df[df["letter_id"] == lid].iloc[0]

    print(lid, ":", sep="")
    for key in gold_fields:
        gold_val = gold_fields[key]
        extracted_val = extracted[key]
        match = "✓" if gold_val == extracted_val else "✗"
        print("  ", key, ": gold=", gold_val, " extracted=", extracted_val, " ", match, sep="")
        total += 1
        if gold_val == extracted_val:
            correct += 1
    print()

print("Accuracy:", correct, "/", total)

# Part 4.2
print("Extraction at temperature=0 (5 runs)")
for i in range(5):
    result = extract_fields(LETTERS["L002"], temperature=0)
    print(i + 1, ". ", result)

print()
print("Extraction at temperature=1.0 (5 runs)")
for i in range(5):
    result = extract_fields(LETTERS["L002"], temperature=1.0)
    print(i + 1, ". ", result)

# Part 4.3
adversarial_texts = {
    "empty": "",
    "irrelevant": "The weather in Accra today is sunny with a high of 31 degrees Celsius.",
    "gibberish": "asdkjf laksjdf 12309 !!! xxxxx loan loan loan",
}

for label, text in adversarial_texts.items():
    print(label, ":")
    result = extract_fields(text, temperature=0)
    print(result)
    print()

"""## Part 4.3 Student Reasoning - Evaluating results
1. The accuracy was 14/18

2. Running the extraction 5 times at both temperature=0 and temperature=1,0 on the same letter produced identicla results. This shows that for narrow, structured tasks with a clear defined output format, temperature has little effect. For production systems, even if temperaature is not set exactly to 0, a tightly scoped ectraction can behave reliably.

3. No the system did not. The "use null, do not guess" intruction was effective.

## Part 4.4 Student Reasoning- Appropriateness

1. Applicants who write poorly in english but have run solid businesses are most at risk. The system judges the content of the letter, so if the business is not expressed well in it, their application would look weak.

2. Sending loan letters with personal information to a third-party API in another country means that personal info leaves Ghana and runs the risk of the data being retained or used by the third-party provider. Before deploying this at a real Ghanaian microfinance institution, I would check the provider's retention policy and look at anonymizing names in the letters.

3. One safeguard would be to make a human officer review applications before any action is taken.

# Section 5 - Reflection
1. Both are processes to improve the quality of output. The difference would be in what is being tuned and how it is measured. Hyperparameters are numeric and can be measured against an accuracy metric where as prompts are often non-numeric and harder to score.

2. No i would not trust the system to run fully unattended. The result that has influenced me is from part 4.2. The extreaction was consistent across temperature but consistency is not the same as correctness. A system can reproduce the same answer every time but still be wrong.

3. Based on response.usage, a simple call used 89 tokens. A full application uses much more than that. I am estimating that roughly above a 1000 tokens will be used per application. Therefore processing 1000 applications a month would take roughly about 1,000,000 tokens a month. This implies that providers should be compared on rate limits.

4. Calling an API beats training a model here because this task needs broad language understanding which would take a huge amount of data to train. Training a model would make sense if the institution needed the system to run completely offline for data privacy.
"""